name: CI

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - uses: jetli/wasm-pack-action@v0.3.0
        with:
          version: 'latest'

      - run: cargo test

      - name: Build node wasm
        working-directory: ./said/wasm
        run: wasm-pack build

      - uses: actions/setup-node@v2
        with:
          node-version: '17.x'
          registry-url: 'https://registry.npmjs.org'
      - working-directory: ./said/wasm/pkg
        run: npm install
      - working-directory: ./said/wasm/pkg
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
